### ISSUE TITLE
Some questions about this work

### ISSUE THREAD

**Issue by musanas** [DannyDainton/postman-docker#1]
Hello Danny,

Good day !
It was nice reading your work with Postman and Docker. It throwed many ideas to me . Kudos to you for that. I thought I will share some of the things that I was trying in this area and get some feedbacks from you.

First of all some idea about how I was dealing with Postman collections

- Like you mentioned I developed all the collections in postman tool and ran with the built in runner
- Once it stabilised I started using Newman cli tool
- For to manage it well and structurize my collections, I created small node app with a package.json
- In the package.json, I added different NPM scripts . The npm scripts are configured with newman run command and passing arguments like invoking collections, global and env files ,and other report generation stuffs etc
- also had a NPM scripts called 'allTests'. so I can concurrently hit on different collections , and all collections will be executed giving back the reports. 
- I also made a 'testenv' npm config varibale in package.json  , and this 'testenv' will be set just before collecton npm script is ran . So he collection can run against any test environemnt that I want.
- So this required Node to be installed in any machine where i want to run this

So I thought about Docker ( Defnitely after reading your work, inspired i should say .. )

- So here, I almost repeated what I have done earlier, but now with the docker file and docker-compose
- Dockerfile designed to use Node and **run the npm config set** and **npm script run**
- Using docker-compose I build the image, and during the build time I pass the build argument which is nothing but the test env against which I want to run the collection like 

> docker-compose build  --build-arg buildtime_testenv=test01
**buildtime_testenv** - is present in dockerfile as ARG
Now the image is ready, but it will always run against only test01 when I run the container.

In order to run the collection against an another testenv i have to build the image again
say like 
> docker-compose build  --build-arg buildtime_testenv=test02

Do you think this is good design of docker collection image ?
Every time I need to build it if I want to run the collection against a diff env , its due to the way I designed the node app where only by setting the npm config variable, the test env is passed as a global varibale to the collection. 
Have you managed your collection to run in a better way against different test urls especially when delaing with docker ?

Thanks in advance for reading my questions

Warm Regards
Musaffir

**Comment by DannyDainton** [comment]
Hey,

Sorry for the late reply - I've only just seen the response :(

Honestly, my Docker knowledge is so minimal I don't think that i'm even able to tell you if that's good or not. If you're rebuilding the image each time, that doesn't sound like an ideal solution, I would take a look into that. The Docker documentation and the community support is really good so I have no doubt that you will find the answers that you're looking for there.

Sorry that I can't be more help.

**Comment by musanas** [comment]
Hello Danny,

Thanks for replying here as well.
I found something better for not to build the image every time .
I made a change to my dockerfile with the below line

CMD bash -c "npm config set cloudpay-api-qa:testEnv env=${PAYROLL_HOST:-test14} && npm run allTests-docker && sleep 1"

its basically a node setup
where i set the env against which the collection need to be run
i set a default value of test14 here
but when the image is running as a container, i can always pass any other env and the urls in the colllection will be modified accordingly and it runs.
